calculator/urls.py
from django.urls import path
from .views import myview, abc

app_name = 'calculator'
urlpatterns = [
    path('', myview, name='calc_form'),
    path('abc', abc, name='abc'),
]

log/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import Home

app_name = 'log'
urlpatterns = [
        path('', Home, name='home'),
]

print/urls.py
from django.urls import path
from .views import print

app_name = 'print'
urlpatterns = [
        path('', print, name='print'),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('calculator/', include('calculator.urls', namespace='calculator')),
    path('log/', include('log.urls', namespace='log')),
    path('backend/', include('backend.urls', namespace='backend')),
    path('print/', include('print.urls', namespace='print')),
]

calculator/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Query(models.Model):
    product_choices = (
        ('HL', 'Home Loan'),
        ('LAP', 'Loan Against Property'),
        ('CV', 'Commercial Vehicle Loan'),
        ('SME', 'SME Loan'),
        ('Corporate', 'Corporate Loan'),
        ('Tractor', 'Tractor Loan'),
        ('AIB', 'Bulk AIB'),
    )
    rating_choices = (
        ('AAA','AAA'),
        ('AA', 'AA'),
        ('A', 'A'),
        ('BBB', 'BBB'),
        ('BB', 'BB'),
        ('U', 'Unrated'),
        ('CM', 'Capital Market'),
        ('CRE', 'CRE'),
        ('CRE_RH','CRE_RH'),
        ('RRE', 'RRE'),
        ('RRP','RRP')
    )
    typ = models.CharField("Type", max_length=4, blank=False)
    ApplNo = models.CharField("Application Number", max_length=25,blank=False)
    RMName = models.CharField("RM's Name", max_length=150, blank=False)
    HRMS = models.CharField("HRMS", max_length=7, blank=False)
    product = models.CharField("Product", max_length=10, blank=False,
                               choices=product_choices)
    sanction_amt = models.IntegerField("Loan Amount", validators=[MinValueValidator(0)],
                                       blank=False)
    roi = models.FloatField("ROI", blank=False)
    tenure = models.IntegerField("Tenure", blank=True, default=60,
                                 validators=[MinValueValidator(0)],)
    utilisation = models.FloatField("Utilisation", default=70.0)
    ltv = models.FloatField("LTV", default=0.0)
    rating = models.CharField("Rating", max_length=10, default=None, null=True,
                              blank=True, choices=rating_choices)
    profee = models.FloatField("Processing Fee", blank=False)
    conpay = models.FloatField("Sourcing Fee", blank=False)
    insur = models.IntegerField("Insurance Premium", validators=[MinValueValidator(0)], blank=False)
    other = models.IntegerField("Other Income", validators=[MinValueValidator(0)], blank=True,
                                default=0)
    recurr = models.BooleanField("Is Other Income Recurring?")
    psl = models.BooleanField("Priority Sector Lending")
    agri_psl = models.BooleanField("Agri Priority Sector Lending")
    rrp = models.BooleanField("Is it RRP?", default=False)
    created = models.DateTimeField(auto_now_add=True)
    ip = models.CharField(default="0.0.0.0", max_length=15, blank=True)

calculator/forms.py
from django import forms
from .models import Query
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML, Fieldset, MultiField, Div, ButtonHolder, Submit, Hidden
from crispy_forms.bootstrap import AppendedText, PrependedText

class TLForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = ('ApplNo','RMName', 'HRMS', 'product', 'sanction_amt',
                  'roi', 'tenure', 'ltv', 'rating', 'profee',
                  'conpay', 'insur', 'other', 'recurr', 'psl', 'agri_psl', 'rrp')
        widgets = {
            'sanction_amt': forms.NumberInput(attrs={'min': 0, 'step': 1000}),
            'roi': forms.NumberInput(attrs={'min': 0}),
            'tenure': forms.NumberInput(attrs={'min': 0}),
            'ltv': forms.NumberInput(attrs={'min': 0}),
            'profee': forms.NumberInput(attrs={'min': 0}),
            'conpay': forms.NumberInput(attrs={'min': 0}),
            'insur': forms.NumberInput(attrs={'min': 0}),
            'other': forms.NumberInput(attrs={'min': 0}),
        }
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Hidden('typ','TL'),
                HTML(
                    """<div class="card-header p-0" id="TLBasicHeader">
                            <h5 class="m-0">
                                <button class="btn w-100 text-left btn-link" data-toggle="collapse" data-target="#TLBasicBody" type="button">
                                    Basic Loan Details <i class="fa fa-lg fa-caret-up float-right" aria-hidden="true"></i>
                                </button>
                            </h5>
                        </div> """
                ),
                Div(
                    Div(
                        "ApplNo",
                        Div(
                            Div('RMName', css_class="col-sm-8"),
                            Div('HRMS', css_class='col-sm-4'),
                            css_class='row'
                        ),
                        'product',
                        css_class="card-body"
                    ),
                    css_id='TLBasicBody', css_class="collapse show active"
                ),
                css_class="card mx-2 shadow my-1 border-0"
            ),
            Div(
                HTML(
                    """
                    <div class="card-header p-0" id="TLFinancialHeader">
                        <h5 class="m-0">
                            <button class="btn w-100 text-left btn-link collapsed" data-toggle="collapse" data-target="#TLFinancialBody" type="button">
                                Financial Details <i class="fa fa-lg fa-caret-down float-right" aria-hidden="true"></i>
                            </button>
                        </h5>
                    </div>
                    """
                ),
                Div(
                    Div(
                        Div(
                            Div(PrependedText('sanction_amt','&#8377'), css_id="magicdiv1", css_class="col-sm-7"),
                            Div(AppendedText('roi','%'), css_id="magicdiv2", css_class="col-sm-5"),
                            Div(AppendedText('tenure','months'), css_id="magicdiv3", css_class="col-sm-6"),
                            Div('rating', AppendedText('ltv','%'), css_id="magicdiv4", css_class="col-sm-6"),
                            css_class='row'
                        ),
                        css_class="card-body"
                    ),
                    css_id="TLFinancialBody", css_class='collapse'
                ),
                css_class="card mx-2 shadow my-1 border-0"
            ),
            Div(
                HTML(
                    """
                    <div class="card-header p-0" id="TLFeeIncomeHeader">
                        <h5 class="mb-0">
                            <button class="btn btn-link w-100 text-left collapsed" type="button" data-toggle="collapse" data-target="#TLFeeIncomeBody" 
                            aria-expanded="false" aria-controls="collapseTwo">
                                Fees and Incomes <i class="fa fa-lg fa-caret-down float-right" aria-hidden="true"></i>
                            </button>
                        </h5>
                    </div>
                    """
                ),
                Div(
                    Div(
                        Div(
                            Div(AppendedText('profee','%'),css_class="col-sm-6"),
                            Div(AppendedText('conpay','%'), css_class="col-sm-6"),
                            Div(PrependedText('insur','&#8377'), css_class="col-sm-6 pr-0"),
                            Div(PrependedText('other','&#8377'), css_class="col-sm-6"),
                            HTML(
                                """
                                <div class="m-2" id="TLrecurr">
                                  <fieldset class="toggle-check large verbal" tabindex="0">
                                    <label>
                                      {{tlform.recurr}}
                                      <span data-on="Yes" data-off="No">
                                        {{tlform.recurr.label_tag}}
                                      </span>
                                    </label>
                                  </fieldset>
                                </div>
                                """
                            ),
                            css_class="row"
                        ),
                        css_class="card-body"
                    ),
                    css_class="collapse", css_id="TLFeeIncomeBody"
                ),
                css_class="card mx-2 shadow my-1 border-0"
            ),
            HTML("""
             <div class="card mx-2 my-1 shadow border-0">
    <div class="card-header p-0" id="TLPLSheader">
      <h5 class="mb-0">
        <button class="btn btn-link w-100 text-left collapsed" type="button" data-toggle="collapse" data-target="#TLPSLBody"
                aria-expanded="false" aria-controls="collapseThree">
          PSL Status <i class="fa fa-lg fa-caret-down float-right" aria-hidden="true"></i>
        </button>
      </h5>
    </div>
    <div id="TLPSLBody" class="collapse" aria-labelledby="headingThree" >
      <div class="card-body">
        <h6 class="card-title">
          Check all that are applicable
        </h6>
        <div class="m-2" id="psl">
          <fieldset class="toggle-check large verbal" tabindex="0">
            <label>
              {{tlform.psl}}
              <span data-on="Yes" data-off="No">
                {{tlform.psl.label_tag}}
              </span>
            </label>
          </fieldset>
        </div>
        <div class="m-2" id="agri_psl">
          <fieldset class="toggle-check large verbal" tabindex="0">
            <label>
              {{tlform.agri_psl}}
              <span data-on="Yes" data-off="No">
                {{tlform.agri_psl.label_tag}}
              </span>
            </label>
          </fieldset>
        </div>
        <div class="m-2" id="rrp">
          <fieldset class="toggle-check large verbal" tabindex="0">
            <label>
              {{tlform.rrp}}
              <span data-on="Yes" data-off="No">
                {{tlform.rrp.label_tag}}
              </span>
            </label>
          </fieldset>
        </div>
      </div>
    </div>
  </div>"""),
            Div(
                Submit('submit','Calculate',css_class="btn btn-primary btn-block"),
                css_class="card mx-2 my-1 shadow border-0"
            )
        )
        super(TLForm, self).__init__(*args, **kwargs)


class ODCCForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = ('ApplNo','RMName', 'HRMS', 'product', 'sanction_amt',
                  'roi', 'utilisation', 'ltv', 'rating', 'profee',
                  'conpay', 'insur', 'other', 'recurr', 'psl', 'agri_psl', 'rrp')
        widgets = {
            'sanction_amt': forms.NumberInput(attrs={'min': 0, 'step': 1000}),
            'roi': forms.NumberInput(attrs={'min': 0}),
            'utilisation': forms.NumberInput(attrs={'min': 0}),
            'ltv': forms.NumberInput(attrs={'min': 0}),
            'profee': forms.NumberInput(attrs={'min': 0}),
            'conpay': forms.NumberInput(attrs={'min': 0}),
            'insur': forms.NumberInput(attrs={'min': 0}),
            'other': forms.NumberInput(attrs={'min': 0}),
        }
    helper = FormHelper()
    helper.layout = Layout(
        AppendedText('roi', '%'),
        AppendedText('profee', '%'),
        AppendedText('conpay', '%'),
        AppendedText('utilisation', '%'),
        PrependedText('sanction_amt', '&#8377'),
        PrependedText('insur', '&#8377'),
        PrependedText('other', '&#8377'),
    )

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Hidden('typ', 'ODCC'),
                HTML(
                    """<div class="card-header p-0" id="ODCCBasicHeader">
                            <h5 class="m-0">
                                <button class="btn w-100 text-left btn-link" data-toggle="collapse" data-target="#ODCCBasicBody" type="button">
                                    Basic Loan Details <i class="fa fa-lg fa-caret-up float-right" aria-hidden="true"></i>
                                </button>
                            </h5>
                        </div> """
                ),
                Div(
                    Div(
                        "ApplNo",
                        Div(
                            Div('RMName', css_class="col-sm-8"),
                            Div('HRMS', css_class='col-sm-4'),
                            css_class='row'
                        ),
                        'product',

calculator/views.py
from django.views.generic.edit import FormView
from django.shortcuts import render
from .classes import Calculator
import pandas as pd
import pickle
from .forms import TLForm, ODCCForm
from django.forms.models import model_to_dict

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def myview(request):
    tlform = TLForm(auto_id='TL%s')
    odccform = ODCCForm(auto_id='ODCC%s')
    if request.method == 'POST':
        typ = request.POST.get('typ')
        if typ == "TL":
            tlform = TLForm(request.POST, auto_id='TL%s')
            dat = tlform.save(commit=False)
            dat.typ = 'TL'
        else:
            odccform = ODCCForm(request.POST, auto_id='ODCC%s')
            dat = odccform.save(commit=False)
            dat.typ = 'ODCC'
        dat.ip = get_client_ip(request)
        dat.save()
        calc = Calculator(**model_to_dict(dat))
        details =  pd.DataFrame.from_dict({
                'Cost/Income (%)': calc.cost_income_ratio * 100,
                'ROA (%)': calc.roa * 100,
                'ROE (%)': calc.roe * 100
            }, orient='index')
        details.columns = ['Year ' + str(i + 1) for i in details.columns]
        if details.shape[1]>10:
            details = details.iloc[:,0:10]
        details = details.round(2).to_html(border=0, classes='table')
        ret = {
            'details': details,
            'total_profit': round(calc.net_profit.sum(), 2),
            'net_roe': round(calc.net_profit.sum() / calc.capital_req.sum() * 100, 2),
            'emi': calc.emi,
            'typ': typ,
            'tlform': tlform,
            'odccform': odccform,
            'ApplNo': request.POST.get('ApplNo')
        }
        return render(request, 'response.html', ret)
    return render(request, 'calculator.html', {'tlform': tlform, 'odccform': odccform})

def abc(request):
    tlform = TLForm(auto_id='TL%s')
    odccform = ODCCForm(auto_id='ODCC%s')
    return render(request, 'temp.html', {'tlform': tlform, 'odccform': odccform})

calculator/templates/calculator.html
{% extends "base.html" %}
 {% load crispy_forms_tags %}
{% load staticfiles %}

{% block title%} Query-Form | Profitability Calculator {% endblock %}
{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'css/calculator.css' %}" >
  <script src="{% static 'js/calculator.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="my-3 col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-10 offset-sm-1">
    <div class="card">
      <h5 class="card-header"> Enter Loan Details</h5>
      <ul class="nav nav-tabs nav-justified">
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#TL">Term Loans</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#ODCC">OD / CC</a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="TL" class="tab-pane  bg mb-0">
          <div class='bg p-3'>
            {% crispy tlform %}
          </div>
        </div>
        <div id="ODCC" class="tab-pane bg mb-0" >
          <div class='bg p-3'>
            {% crispy odccform %}
          </div>
        </div>
      </div>
    </div>
  </div>
<br><br><br>

{% endblock %}

calculator/templates/response.html
{% extends "base.html" %}
 {% load crispy_forms_tags %}
{% load staticfiles %}
{% block title%} Response | Profitability Calculator {% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'css/calculator.css' %}" >
  <script src="{% static 'js/calculator.js' %}"></script>
{% endblock %}


{% block content %}
  <div class="row m-2">
    <div class="my-3 col-lg-4 col-md-6 col-sm-10 ">
     <div class="card">
      <h5 class="card-header"> Enter Loan Details</h5>
      <ul class="nav nav-tabs nav-justified">
        <li class="nav-item">
          <a class="nav-link {% if typ == 'TL' %} active show {% endif %}" id = "TLLink" data-toggle="tab" href="#TL">Term Loans</a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if typ == 'ODCC' %} active show {% endif %}"" id = "ODCCLink" data-toggle="tab" href="#ODCC">OD / CC</a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="TL" class="tab-pane{% if typ == 'TL' %} active show {% endif %}"  bg mb-0">
          <div class='bg p-3'>
            {% crispy tlform %}
          </div>
        </div>
        <div id="ODCC" class="tab-pane {% if typ == 'ODCC' %} active show {% endif %}"bg mb-0" >
          <div class='bg p-3'>
            {% crispy odccform %}
          </div>
        </div>
      </div>
    </div>
    </div> <!-- The Form Element--->
    <div class="my-3 col-lg-8">
      <div class="card">
        <h5 class="card-header">
          Profitability Chart
        </h5>
        <div class="card-body">
          <div class="container shadow"> </div>
          <h5 class="card-heading text-center shadow"> Lifetime ROE: <span class="font-weight-light">{{net_roe}}%</span></h5>
          <div class="table-responsive shadow">
  {{details|safe}}
  </div>
        </div>
      </div>
        <div class="my-5 d-flex justify-content-center">
    <form class="form form-inline" action="{% url 'print:print'%}" method="post">
      {% csrf_token %}
            <input hidden name="ApplNo" value="{{ApplNo}}">
            <input type="submit" value="Print Final Calculations" class="btn btn-danger">
    </form>
  </div>
    </div>   <!-- Output Table--->
  </div>

<br><br><br>
{% endblock %}

calculator/templates/temp.html
{% extends "base.html" %}
 {% load crispy_forms_tags %}
{% load staticfiles %}


{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'css/calculator.css' %}" >
  <script src="{% static 'js/calculator.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="my-3 col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-10 offset-sm-1">
    <div class="card">
      <h5 class="card-header"> Enter Loan Details</h5>
      <ul class="nav nav-tabs nav-justified">
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#TL">Term Loans</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#ODCC">OD / CC</a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="TL" class="tab-pane  bg mb-0">
          <div class='bg p-3'>
          {% crispy tlform %}
          </div>
        </div>
        <div id="ODCC" class="tab-pane bg mb-0" >
          <div class='bg p-3'>
          {% crispy odccform %}
        </div>
      </div>
    </div>
  </div>
</main>

<br><br><br>
{% endblock %}