calculator/urls.py
from django.urls import path
from .views import myview, abc

app_name = 'calculator'
urlpatterns = [
    path('', myview, name='calc_form'),
    path('abc', abc, name='abc'),
]

log/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import Home

app_name = 'log'
urlpatterns = [
        path('', Home, name='home'),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('calculator/', include('calculator.urls', namespace='calculator')),
    path('log/', include('log.urls', namespace='log')),
    path('backend/', include('backend.urls', namespace='backend')),
    path('print/', include('print.urls', namespace='print')),
]

webproject/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}DCB Bank | Profitability Calculator{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' type='image/x-icon' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" >
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
     {% block stylesheets %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded sticky-top">
      <a class="navbar-brand" href="http://www.dcbbank.com"><img src="{% static 'images/logo.png'%}" style="width:130px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item" id="Home">
            <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'calculator:calc_form' %}">Calculator</a>
          </li>
        </ul>
          {% if user.is_authenticated %}
            <a class="nav-link" href="">Logout</a>
          {% else %}
            <a class="nav-link" href="{% url 'log:home'%}">Login</a>
          {% endif %}
      </div>
    </nav>
    <main role="main">
      {% block content %}
      {% endblock %}
      <hr>
    </main>
    <footer>
      <div class="container">
        <p> &copy; DCB Bank 2018-2019</p>
      </div>
    </footer>
  </body>
</html>