calculator/urls.py
from django.urls import path
from .views import myview, abc

app_name = 'calculator'
urlpatterns = [
    path('', myview, name='calc_form'),
    path('abc', abc, name='abc'),
]

homepage/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = 'homepage'
urlpatterns = [
        path('', TemplateView.as_view(template_name="home.html"), name='home'),
]

log/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import Home

app_name = 'log'
urlpatterns = [
        path('', Home, name='home'),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('calculator/', include('calculator.urls', namespace='calculator')),
    path('log/', include('log.urls', namespace='log')),
    path('backend/', include('backend.urls', namespace='backend')),
    path('print/', include('print.urls', namespace='print')),
]

homepage/views.py
from django.shortcuts import render, HttpResponse

def Home(request):
    return HttpResponse('this is home')

homepage/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title%} Home| Profitability Calculator {% endblock %}

{% block stylesheets %} <link rel="stylesheet" href="{% static 'css/home.css' %}" > {% endblock %}

{% block content %}
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Profitability Calculator</h1><br>
        <p class="lead text-muted">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse orci ex, dignissim vel nibh at, euismod euismod tortor. Phasellus commodo non
          justo sit amet facilisis. In a arcu luctus, dapibus nunc id, dapibus nunc. Nulla at dolor erat. Ut ultricies risus pretium suscipit fermentum. Duis
          magna arcu, porttitor id molestie ut, auctor pulvinar velit. Quisque suscipit nibh eget massa commodo maximus.
        </p>
        <p>
          <a href="{% url 'calculator:calc_form' %}" class="btn btn-primary my-2 mr-2">Go to Calculator</a>
          <a href="{% url 'backend:home' %}" class="btn btn-secondary my-2 ml-2">Access Admin Portal</a>
        </p>
      </div>
    </section>
{% endblock %}S